export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';

export const LOAD_DOCUMENTS_SUCCESS = 'LOAD_DOCUMENTS_SUCCESS';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENTS_SUCCESS = 'DELETE_DOCUMENTS_SUCCESS';

export const INCREMENT_PAGE_NUMBER = 'INCREMENT_PAGE_NUMBER';
export const DECREMENT_PAGE_NUMBER = 'DECREMENT_PAGE_NUMBER';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

export const LOAD_ROLES_SUCCESS = 'LOAD_ROLES_SUCCESS';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
